// Code generated by jmx_codegen; DO NOT EDIT.

package jmaxml

import "time"

type IbHead struct {
	Title           string           `xml:"Title" json:"title"`
	ReportDateTime  time.Time        `xml:"ReportDateTime" json:"reportDateTime"`
	TargetDateTime  NullableDateTime `xml:"TargetDateTime" json:"targetDateTime"`
	TargetDTDubious *string          `xml:"TargetDTDubious" json:"targetDTDubious,omitempty"`
	TargetDuration  *Duration        `xml:"TargetDuration" json:"targetDuration,omitempty"`
	ValidDateTime   *time.Time       `xml:"ValidDateTime" json:"validDateTime,omitempty"`
	EventID         string           `xml:"EventID" json:"eventID"`
	InfoType        string           `xml:"InfoType" json:"infoType"`
	Serial          string           `xml:"Serial" json:"serial"`
	InfoKind        string           `xml:"InfoKind" json:"infoKind"`
	InfoKindVersion string           `xml:"InfoKindVersion" json:"infoKindVersion"`
	Headline        IbHeadline       `xml:"Headline" json:"headline"`
}

type IbHeadline struct {
	Text         string           `xml:"Text" json:"text"`
	Informations []*IbInformation `xml:"Information" json:"informations,omitempty"`
}

type IbInformation struct {
	Type  string    `xml:"type,attr" json:"type"`
	Items []*IbItem `xml:"Item" json:"items"`
}

type IbItem struct {
	Kinds     []*IbKind `xml:"Kind" json:"kinds"`
	LastKinds []*IbKind `xml:"LastKind" json:"lastKinds,omitempty"`
	Areas     IbAreas   `xml:"Areas" json:"areas"`
}

type IbKind struct {
	Name      string  `xml:"Name" json:"name"`
	Code      *string `xml:"Code" json:"code,omitempty"`
	Condition *string `xml:"Condition" json:"condition,omitempty"`
}

type IbAreas struct {
	CodeType string    `xml:"codeType,attr" json:"codeType"`
	Areas    []*IbArea `xml:"Area" json:"areas"`
}

type IbArea struct {
	Name        string          `xml:"Name" json:"name"`
	Code        *string         `xml:"Code" json:"code,omitempty"`
	Circles     []*EbCircle     `xml:"Circle" json:"circles,omitempty"`
	Coordinates []*EbCoordinate `xml:"Coordinate" json:"coordinates,omitempty"`
	Lines       []*EbCoordinate `xml:"Line" json:"lines,omitempty"`
	Polygons    []*EbCoordinate `xml:"Polygon" json:"polygons,omitempty"`
}
