// Code generated by jmx_codegen; DO NOT EDIT.

package jmaxml

import "time"

type Report struct {
	Control  Control   `xml:"Control" json:"control"`
	Head     IbHead    `xml:"Head" json:"head"`
	MeteBody *MeteBody `xml:"http://xml.kishou.go.jp/jmaxml1/body/meteorology1/ Body" json:"jmx_meteBody,omitempty"`
	SeisBody *SeisBody `xml:"http://xml.kishou.go.jp/jmaxml1/body/seismology1/ Body" json:"jmx_seisBody,omitempty"`
	VolcBody *VolcBody `xml:"http://xml.kishou.go.jp/jmaxml1/body/volcanology1/ Body" json:"jmx_volcBody,omitempty"`
}

type Control struct {
	Title             string     `xml:"Title" json:"title"`
	DateTime          time.Time  `xml:"DateTime" json:"dateTime"`
	Status            string     `xml:"Status" json:"status"`
	EditorialOffice   string     `xml:"EditorialOffice" json:"editorialOffice"`
	PublishingOffices StringList `xml:"PublishingOffice" json:"publishingOffices"`
}
