// Code generated by jmx_codegen; DO NOT EDIT.

package jmaxml

import "time"

type MeteBody struct {
	TargetArea          *MeteArea                  `xml:"TargetArea" json:"targetArea,omitempty"`
	Notices             []string                   `xml:"Notice" json:"notices,omitempty"`
	Warnings            []*MeteWarning             `xml:"Warning" json:"warnings,omitempty"`
	MeteorologicalInfos []*MeteMeteorologicalInfos `xml:"MeteorologicalInfos" json:"meteorologicalInfoses,omitempty"`
	Comment             *MeteComment               `xml:"Comment" json:"comment,omitempty"`
	OfficeInfo          *MeteOfficeInfo            `xml:"OfficeInfo" json:"officeInfo,omitempty"`
	AdditionalInfo      *MeteAdditionalInfo        `xml:"AdditionalInfo" json:"additionalInfo,omitempty"`
}

type MeteWarning struct {
	Type  string      `xml:"type,attr" json:"type"`
	Items []*MeteItem `xml:"Item" json:"items"`
}

type MeteMeteorologicalInfos struct {
	Type                string                    `xml:"type,attr" json:"type"`
	MeteorologicalInfos []*MeteMeteorologicalInfo `xml:"MeteorologicalInfo" json:"meteorologicalInfos,omitempty"`
	TimeSeriesInfos     []*MeteTimeSeriesInfo     `xml:"TimeSeriesInfo" json:"timeSeriesInfos,omitempty"`
}

type MeteMeteorologicalInfo struct {
	Type     *string     `xml:"type,attr" json:"type,omitempty"`
	DateTime EbDateTime  `xml:"DateTime" json:"dateTime"`
	Duration *Duration   `xml:"Duration" json:"duration,omitempty"`
	Name     *string     `xml:"Name" json:"name,omitempty"`
	Items    []*MeteItem `xml:"Item" json:"items"`
}

type MeteTimeSeriesInfo struct {
	TimeDefines MeteTimeDefines `xml:"TimeDefines" json:"timeDefines"`
	Items       []*MeteItem     `xml:"Item" json:"items"`
}

type MeteTimeDefines struct {
	TimeDefines []*MeteTimeDefine `xml:"TimeDefine" json:"timeDefines"`
}

type MeteTimeDefine struct {
	TimeId   uint8      `xml:"timeId,attr" json:"timeId"`
	DateTime EbDateTime `xml:"DateTime" json:"dateTime"`
	Duration *Duration  `xml:"Duration" json:"duration,omitempty"`
	Name     *string    `xml:"Name" json:"name,omitempty"`
}

type MeteAdditionalInfo struct {
	ObservationAddition     *MeteObservationAddition     `xml:"ObservationAddition" json:"observationAddition,omitempty"`
	ClimateForecastAddition *MeteClimateForecastAddition `xml:"ClimateForecastAddition" json:"climateForecastAddition,omitempty"`
	FloodForecastAddition   *MeteFloodForecastAddition   `xml:"FloodForecastAddition" json:"floodForecastAddition,omitempty"`
}

type MeteClimateForecastAddition struct {
	TargetDateTimeNotice  *string                 `xml:"TargetDateTimeNotice" json:"targetDateTimeNotice,omitempty"`
	NextForecastSchedules []*MeteForecastSchedule `xml:"NextForecastSchedule" json:"nextForecastSchedules,omitempty"`
	NoticeOfSchedule      *string                 `xml:"NoticeOfSchedule" json:"noticeOfSchedule,omitempty"`
	AdditionalNotice      *string                 `xml:"AdditionalNotice" json:"additionalNotice,omitempty"`
}

type MeteForecastSchedule struct {
	Target   string     `xml:"target,attr" json:"target"`
	Text     *string    `xml:"Text" json:"text,omitempty"`
	DateTime *time.Time `xml:"DateTime" json:"dateTime,omitempty"`
}

type MeteComment struct {
	Texts []*MeteText `xml:"Text" json:"texts"`
	Code  *StringList `xml:"Code" json:"code,omitempty"`
}

type MeteText struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr" json:"type"`
}

type MeteItem struct {
	Kinds        []*MeteKind   `xml:"Kind" json:"kinds"`
	Areas        *MeteAreas    `xml:"Areas" json:"areas,omitempty"`
	Stations     *MeteStations `xml:"Stations" json:"stations,omitempty"`
	Area         *MeteArea     `xml:"Area" json:"area,omitempty"`
	Station      *MeteStation  `xml:"Station" json:"station,omitempty"`
	ChangeStatus *string       `xml:"ChangeStatus" json:"changeStatus,omitempty"`
	FullStatus   *string       `xml:"FullStatus" json:"fullStatus,omitempty"`
	EditingMark  *string       `xml:"EditingMark" json:"editingMark,omitempty"`
	OtherReports []string      `xml:"OtherReport" json:"otherReports,omitempty"`
}

type MeteKind struct {
	Name          *string            `xml:"Name" json:"name,omitempty"`
	Code          *string            `xml:"Code" json:"code,omitempty"`
	Status        *string            `xml:"Status" json:"status,omitempty"`
	ClassName     *string            `xml:"ClassName" json:"className,omitempty"`
	Condition     *string            `xml:"Condition" json:"condition,omitempty"`
	LastKind      *MeteNextKind      `xml:"LastKind" json:"lastKind,omitempty"`
	NextKinds     *MeteNextKinds     `xml:"NextKinds" json:"nextKinds,omitempty"`
	Attention     *MeteAttention     `xml:"Attention" json:"attention,omitempty"`
	WarningNotice *MeteWarningNotice `xml:"WarningNotice" json:"warningNotice,omitempty"`
	Addition      *MeteAddition      `xml:"Addition" json:"addition,omitempty"`
	DateTime      *EbDateTime        `xml:"DateTime" json:"dateTime,omitempty"`
	Properties    []*MeteProperty    `xml:"Property" json:"properties,omitempty"`
}

type MeteNextKinds struct {
	NextKinds []*MeteNextKind `xml:"NextKind" json:"nextKinds"`
}

type MeteNextKind struct {
	Name      string      `xml:"Name" json:"name"`
	Code      string      `xml:"Code" json:"code"`
	Condition *string     `xml:"Condition" json:"condition,omitempty"`
	DateTime  *EbDateTime `xml:"DateTime" json:"dateTime,omitempty"`
	Sentence  *string     `xml:"Sentence" json:"sentence,omitempty"`
}

type MeteAttention struct {
	Notes []string `xml:"Note" json:"notes"`
}

type MeteWarningNotice struct {
	StartTime MeteForecastTerm `xml:"StartTime" json:"startTime"`
	Note      string           `xml:"Note" json:"note"`
}

type MeteForecastTerm struct {
	Date *string `xml:"Date" json:"date,omitempty"`
	Term *string `xml:"Term" json:"term,omitempty"`
}

type MeteAddition struct {
	Notes []string `xml:"Note" json:"notes"`
}

type MeteProperty struct {
	Type                           string                              `xml:"Type" json:"type"`
	SignificancyParts              []*MeteSignificancyPart             `xml:"SignificancyPart" json:"significancyParts,omitempty"`
	SubsequentSignificancyParts    []*MeteSignificancyPart             `xml:"SubsequentSignificancyPart" json:"subsequentSignificancyParts,omitempty"`
	WarningPeriod                  *MetePeriod                         `xml:"WarningPeriod" json:"warningPeriod,omitempty"`
	AdvisoryPeriod                 *MetePeriod                         `xml:"AdvisoryPeriod" json:"advisoryPeriod,omitempty"`
	PeakTime                       *MeteForecastTerm                   `xml:"PeakTime" json:"peakTime,omitempty"`
	DetailForecast                 *MeteDetailForecast                 `xml:"DetailForecast" json:"detailForecast,omitempty"`
	WindPart                       *MeteWindPart                       `xml:"WindPart" json:"windPart,omitempty"`
	WindDirectionPart              *MeteWindDirectionPart              `xml:"WindDirectionPart" json:"windDirectionPart,omitempty"`
	WindSpeedPart                  *MeteWindSpeedPart                  `xml:"WindSpeedPart" json:"windSpeedPart,omitempty"`
	WarningAreaParts               []*MeteWarningAreaPart              `xml:"WarningAreaPart" json:"warningAreaParts,omitempty"`
	WeatherPart                    *MeteWeatherPart                    `xml:"WeatherPart" json:"weatherPart,omitempty"`
	PressurePart                   *MetePressurePart                   `xml:"PressurePart" json:"pressurePart,omitempty"`
	TemperaturePart                *MeteTemperaturePart                `xml:"TemperaturePart" json:"temperaturePart,omitempty"`
	VisibilityPart                 *MeteVisibilityPart                 `xml:"VisibilityPart" json:"visibilityPart,omitempty"`
	SynopsisPart                   *MeteSynopsisPart                   `xml:"SynopsisPart" json:"synopsisPart,omitempty"`
	WaveHeightPart                 *MeteWaveHeightPart                 `xml:"WaveHeightPart" json:"waveHeightPart,omitempty"`
	PrecipitationParts             []*MetePrecipitationPart            `xml:"PrecipitationPart" json:"precipitationParts,omitempty"`
	SnowfallDepthPart              *MeteSnowfallDepthPart              `xml:"SnowfallDepthPart" json:"snowfallDepthPart,omitempty"`
	SnowDepthPart                  *MeteSnowDepthPart                  `xml:"SnowDepthPart" json:"snowDepthPart,omitempty"`
	HumidityParts                  []*MeteHumidityPart                 `xml:"HumidityPart" json:"humidityParts,omitempty"`
	TidalLevelPart                 *MeteTidalLevelPart                 `xml:"TidalLevelPart" json:"tidalLevelPart,omitempty"`
	SunshinePart                   *MeteSunshinePart                   `xml:"SunshinePart" json:"sunshinePart,omitempty"`
	WeatherCodePart                *MeteWeatherCodePart                `xml:"WeatherCodePart" json:"weatherCodePart,omitempty"`
	ProbabilityOfPrecipitationPart *MeteProbabilityOfPrecipitationPart `xml:"ProbabilityOfPrecipitationPart" json:"probabilityOfPrecipitationPart,omitempty"`
	SeaIcePart                     *MeteSeaIcePart                     `xml:"SeaIcePart" json:"seaIcePart,omitempty"`
	IcingPart                      *MeteIcingPart                      `xml:"IcingPart" json:"icingPart,omitempty"`
	ReliabilityClassPart           *MeteReliabilityClassPart           `xml:"ReliabilityClassPart" json:"reliabilityClassPart,omitempty"`
	ReliabilityValuePart           *MeteReliabilityValuePart           `xml:"ReliabilityValuePart" json:"reliabilityValuePart,omitempty"`
	ClassPart                      *MeteClassPart                      `xml:"ClassPart" json:"classPart,omitempty"`
	PossibilityRankOfWarningPart   *MetePossibilityRankOfWarningPart   `xml:"PossibilityRankOfWarningPart" json:"possibilityRankOfWarningPart,omitempty"`
	TyphoonNamePart                *MeteTyphoonNamePart                `xml:"TyphoonNamePart" json:"typhoonNamePart,omitempty"`
	CenterPart                     *MeteCenterPart                     `xml:"CenterPart" json:"centerPart,omitempty"`
	CoordinatePart                 *MeteCoordinatePart                 `xml:"CoordinatePart" json:"coordinatePart,omitempty"`
	IsobarPart                     *MeteIsobarPart                     `xml:"IsobarPart" json:"isobarPart,omitempty"`
	WaterLevelPart                 *MeteWaterLevelPart                 `xml:"WaterLevelPart" json:"waterLevelPart,omitempty"`
	FloodAssumptionTable           *MeteFloodAssumptionTable           `xml:"FloodAssumptionTable" json:"floodAssumptionTable,omitempty"`
	DischargePart                  *MeteDischargePart                  `xml:"DischargePart" json:"dischargePart,omitempty"`
	ClimateFeatureParts            []*EbClimateFeature                 `xml:"ClimateFeaturePart" json:"climateFeatureParts,omitempty"`
	ClimateValuesParts             []*MeteClimateValuesPart            `xml:"ClimateValuesPart" json:"climateValuesParts,omitempty"`
	ClimateProbabilityValuesPart   *MeteClimateProbabilityValuesPart   `xml:"ClimateProbabilityValuesPart" json:"climateProbabilityValuesPart,omitempty"`
	EventDatePart                  *MeteEventDatePart                  `xml:"EventDatePart" json:"eventDatePart,omitempty"`
	PrecipitationClassPart         *EbClassThresholdOfAverage          `xml:"PrecipitationClassPart" json:"precipitationClassPart,omitempty"`
	SolarZenithAnglePart           *MeteSolarZenithAnglePart           `xml:"SolarZenithAnglePart" json:"solarZenithAnglePart,omitempty"`
	UvIndexPart                    *MeteUvIndexPart                    `xml:"UvIndexPart" json:"uvIndexPart,omitempty"`
	FiftyKtWindProbabilityParts    []*MeteFiftyKtWindProbabilityPart   `xml:"FiftyKtWindProbabilityPart" json:"fiftyKtWindProbabilityParts,omitempty"`
	Texts                          []*EbReferableString                `xml:"Text" json:"texts,omitempty"`
}

type MeteClimateValuesPart struct {
	Type           string             `xml:"type,attr" json:"type"`
	Temperatures   []*EbTemperature   `xml:"Temperature" json:"temperatures,omitempty"`
	Precipitations []*EbPrecipitation `xml:"Precipitation" json:"precipitations,omitempty"`
	Sunshines      []*EbSunshine      `xml:"Sunshine" json:"sunshines,omitempty"`
	SnowfallDepths []*EbSnowfallDepth `xml:"SnowfallDepth" json:"snowfallDepths,omitempty"`
	SnowDepths     []*EbSnowDepth     `xml:"SnowDepth" json:"snowDepths,omitempty"`
	Comparisons    []*EbComparison    `xml:"Comparison" json:"comparisons,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteEventDatePart struct {
	Dates     []*MeteEventDate `xml:"Date" json:"dates,omitempty"`
	Normals   []*MeteEventDate `xml:"Normal" json:"normals,omitempty"`
	LastYears []*MeteEventDate `xml:"LastYear" json:"lastYears,omitempty"`
	Remark    *string          `xml:"Remark" json:"remark,omitempty"`
}

type MeteEventDate struct {
	Value       string  `xml:",chardata"`
	Description *string `xml:"description,attr" json:"description,omitempty"`
	Dubious     *string `xml:"dubious,attr" json:"dubious,omitempty"`
}

type MeteClimateProbabilityValuesPart struct {
	ClimateProbabilityValues []*EbClimateProbabilityValues `xml:"ClimateProbabilityValues" json:"climateProbabilityValueses"`
}

type MeteSolarZenithAnglePart struct {
	SolarZenithAngles []*EbSolarZenithAngle `xml:"SolarZenithAngle" json:"solarZenithAngles"`
}

type MeteUvIndexPart struct {
	UvIndexes []*EbUvIndex `xml:"UvIndex" json:"uvIndexes"`
	Text      *string      `xml:"Text" json:"text,omitempty"`
}

type MeteFiftyKtWindProbabilityPart struct {
	FiftyKtWindProbabilities []*EbWeatherForecastProbability `xml:"FiftyKtWindProbability" json:"fiftyKtWindProbabilities"`
}

type MetePeriod struct {
	StartTime *MeteForecastTerm `xml:"StartTime" json:"startTime,omitempty"`
	EndTime   *MeteForecastTerm `xml:"EndTime" json:"endTime,omitempty"`
	OverTime  *string           `xml:"OverTime" json:"overTime,omitempty"`
	ZoneTime  *MeteForecastTerm `xml:"ZoneTime" json:"zoneTime,omitempty"`
}

type MeteAreas struct {
	CodeType *string     `xml:"codeType,attr" json:"codeType,omitempty"`
	Areas    []*MeteArea `xml:"Area" json:"areas"`
}

type MeteStations struct {
	CodeType *string        `xml:"codeType,attr" json:"codeType,omitempty"`
	Stations []*MeteStation `xml:"Station" json:"stations"`
}

type MeteArea struct {
	CodeType              *string             `xml:"codeType,attr" json:"codeType,omitempty"`
	Name                  string              `xml:"Name" json:"name"`
	Code                  *string             `xml:"Code" json:"code,omitempty"`
	Prefecture            *MetePrefectureCity `xml:"Prefecture" json:"prefecture,omitempty"`
	PrefectureCode        *string             `xml:"PrefectureCode" json:"prefectureCode,omitempty"`
	PrefectureList        *StringList         `xml:"PrefectureList" json:"prefectureList,omitempty"`
	PrefectureCodeList    *StringList         `xml:"PrefectureCodeList" json:"prefectureCodeList,omitempty"`
	SubPrefecture         *string             `xml:"SubPrefecture" json:"subPrefecture,omitempty"`
	SubPrefectureCode     *string             `xml:"SubPrefectureCode" json:"subPrefectureCode,omitempty"`
	SubPrefectureList     *StringList         `xml:"SubPrefectureList" json:"subPrefectureList,omitempty"`
	SubPrefectureCodeList *StringList         `xml:"SubPrefectureCodeList" json:"subPrefectureCodeList,omitempty"`
	City                  *MetePrefectureCity `xml:"City" json:"city,omitempty"`
	CityCode              *string             `xml:"CityCode" json:"cityCode,omitempty"`
	CityList              *StringList         `xml:"CityList" json:"cityList,omitempty"`
	CityCodeList          *StringList         `xml:"CityCodeList" json:"cityCodeList,omitempty"`
	SubCity               *string             `xml:"SubCity" json:"subCity,omitempty"`
	SubCityCode           *string             `xml:"SubCityCode" json:"subCityCode,omitempty"`
	SubCityList           *StringList         `xml:"SubCityList" json:"subCityList,omitempty"`
	SubCityCodeList       *StringList         `xml:"SubCityCodeList" json:"subCityCodeList,omitempty"`
	Circles               []*EbCircle         `xml:"Circle" json:"circles,omitempty"`
	Coordinates           []*EbCoordinate     `xml:"Coordinate" json:"coordinates,omitempty"`
	Lines                 []*EbCoordinate     `xml:"Line" json:"lines,omitempty"`
	Polygons              []*EbCoordinate     `xml:"Polygon" json:"polygons,omitempty"`
	Location              *string             `xml:"Location" json:"location,omitempty"`
	Status                *string             `xml:"Status" json:"status,omitempty"`
}

type MetePrefectureCity struct {
	Value    string  `xml:",chardata"`
	PartType *string `xml:"partType,attr" json:"partType,omitempty"`
}

type MeteStation struct {
	Name        string             `xml:"Name" json:"name"`
	Codes       []*MeteStationCode `xml:"Code" json:"codes"`
	Location    *string            `xml:"Location" json:"location,omitempty"`
	Status      *string            `xml:"Status" json:"status,omitempty"`
	Coordinates []*EbCoordinate    `xml:"Coordinate" json:"coordinates,omitempty"`
}

type MeteStationCode struct {
	Value string  `xml:",chardata"`
	Type  *string `xml:"type,attr" json:"type,omitempty"`
}

type MeteOfficeInfo struct {
	Offices []*MeteOffice `xml:"Office" json:"offices"`
}

type MeteOffice struct {
	Type        string  `xml:"type,attr" json:"type"`
	Name        string  `xml:"Name" json:"name"`
	Code        *string `xml:"Code" json:"code,omitempty"`
	ContactInfo string  `xml:"ContactInfo" json:"contactInfo"`
	URI         *string `xml:"URI" json:"uRI,omitempty"`
}

type MeteObservationAddition struct {
	DeviationFromNormal   *string `xml:"DeviationFromNormal" json:"deviationFromNormal,omitempty"`
	DeviationFromLastYear *string `xml:"DeviationFromLastYear" json:"deviationFromLastYear,omitempty"`
	Text                  *string `xml:"Text" json:"text,omitempty"`
}

type MeteFloodForecastAddition struct {
	HydrometricStationParts []*MeteHydrometricStationPart `xml:"HydrometricStationPart" json:"hydrometricStationParts"`
}

type MeteWindPart struct {
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseWind      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseWind    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseWind    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas       []*MeteSubAreaWind `xml:"SubArea" json:"subAreas,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	WindDegrees    []*EbWindDegree    `xml:"WindDegree" json:"windDegrees,omitempty"`
	WindSpeeds     []*EbWindSpeed     `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	WindScales     []*EbWindScale     `xml:"WindScale" json:"windScales,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaWind struct {
	AreaName       *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseWind      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseWind    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseWind    `xml:"Becoming" json:"becomings,omitempty"`
	Locals         []*MeteLocalWind   `xml:"Local" json:"locals,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	WindDegrees    []*EbWindDegree    `xml:"WindDegree" json:"windDegrees,omitempty"`
	WindSpeeds     []*EbWindSpeed     `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	WindScales     []*EbWindScale     `xml:"WindScale" json:"windScales,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseWind struct {
	TimeModifier   *string            `xml:"TimeModifier" json:"timeModifier,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	WindDegrees    []*EbWindDegree    `xml:"WindDegree" json:"windDegrees,omitempty"`
	WindSpeeds     []*EbWindSpeed     `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	WindScales     []*EbWindScale     `xml:"WindScale" json:"windScales,omitempty"`
	Locals         []*MeteLocalWind   `xml:"Local" json:"locals,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalWind struct {
	AreaName       *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	WindDegrees    []*EbWindDegree    `xml:"WindDegree" json:"windDegrees,omitempty"`
	WindSpeeds     []*EbWindSpeed     `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	WindScales     []*EbWindScale     `xml:"WindScale" json:"windScales,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteSentence struct {
	Value string  `xml:",chardata"`
	Type  *string `xml:"type,attr" json:"type,omitempty"`
}

type MeteWindDirectionPart struct {
	Sentence       *MeteSentence               `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseWindDirection      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseWindDirection    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseWindDirection    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas       []*MeteSubAreaWindDirection `xml:"SubArea" json:"subAreas,omitempty"`
	WindDirections []*EbWindDirection          `xml:"WindDirection" json:"windDirections,omitempty"`
	Time           *time.Time                  `xml:"Time" json:"time,omitempty"`
	Remark         *string                     `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaWindDirection struct {
	AreaName       *string                   `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence             `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseWindDirection    `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseWindDirection  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseWindDirection  `xml:"Becoming" json:"becomings,omitempty"`
	Locals         []*MeteLocalWindDirection `xml:"Local" json:"locals,omitempty"`
	WindDirections []*EbWindDirection        `xml:"WindDirection" json:"windDirections,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseWindDirection struct {
	TimeModifier   *string                   `xml:"TimeModifier" json:"timeModifier,omitempty"`
	WindDirections []*EbWindDirection        `xml:"WindDirection" json:"windDirections,omitempty"`
	Locals         []*MeteLocalWindDirection `xml:"Local" json:"locals,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalWindDirection struct {
	AreaName       *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteWindSpeedPart struct {
	Sentence        *MeteSentence           `xml:"Sentence" json:"sentence,omitempty"`
	Base            *MeteBaseWindSpeed      `xml:"Base" json:"base,omitempty"`
	Temporaries     []*MeteBaseWindSpeed    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings       []*MeteBaseWindSpeed    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas        []*MeteSubAreaWindSpeed `xml:"SubArea" json:"subAreas,omitempty"`
	WindSpeeds      []*EbWindSpeed          `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	WindSpeedLevels []*MeteWindSpeedLevel   `xml:"WindSpeedLevel" json:"windSpeedLevels,omitempty"`
	Time            *time.Time              `xml:"Time" json:"time,omitempty"`
	Remark          *string                 `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaWindSpeed struct {
	AreaName    *string               `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence         `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWindSpeed    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWindSpeed  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWindSpeed  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalWindSpeed `xml:"Local" json:"locals,omitempty"`
	WindSpeeds  []*EbWindSpeed        `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	Time        *time.Time            `xml:"Time" json:"time,omitempty"`
	Remark      *string               `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseWindSpeed struct {
	TimeModifier *string               `xml:"TimeModifier" json:"timeModifier,omitempty"`
	WindSpeeds   []*EbWindSpeed        `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	Locals       []*MeteLocalWindSpeed `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time            `xml:"Time" json:"time,omitempty"`
	Remark       *string               `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalWindSpeed struct {
	AreaName   *string        `xml:"AreaName" json:"areaName,omitempty"`
	Sentence   *MeteSentence  `xml:"Sentence" json:"sentence,omitempty"`
	WindSpeeds []*EbWindSpeed `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	Time       *time.Time     `xml:"Time" json:"time,omitempty"`
	Remark     *string        `xml:"Remark" json:"remark,omitempty"`
}

type MeteWindSpeedLevel struct {
	Value       NullableFloat `xml:",chardata"`
	Type        string        `xml:"type,attr" json:"type"`
	RefID       uint8         `xml:"refID,attr" json:"refID"`
	Description *string       `xml:"description,attr" json:"description,omitempty"`
	Range       StringList    `xml:"range,attr" json:"range"`
}

type MeteWarningAreaPart struct {
	Type       string         `xml:"type,attr" json:"type"`
	WindSpeeds []*EbWindSpeed `xml:"WindSpeed" json:"windSpeeds"`
	Circle     EbCircle       `xml:"Circle" json:"circle"`
}

type MeteWeatherPart struct {
	Sentence    *MeteSentence         `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWeather      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWeather    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWeather    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaWeather `xml:"SubArea" json:"subAreas,omitempty"`
	Weathers    []*EbWeather          `xml:"Weather" json:"weathers,omitempty"`
	Time        *time.Time            `xml:"Time" json:"time,omitempty"`
	Remark      *string               `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaWeather struct {
	AreaName    *string             `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence       `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWeather    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWeather  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWeather  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalWeather `xml:"Local" json:"locals,omitempty"`
	Weathers    []*EbWeather        `xml:"Weather" json:"weathers,omitempty"`
	Time        *time.Time          `xml:"Time" json:"time,omitempty"`
	Remark      *string             `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseWeather struct {
	TimeModifier *string             `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Weathers     []*EbWeather        `xml:"Weather" json:"weathers,omitempty"`
	Locals       []*MeteLocalWeather `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time          `xml:"Time" json:"time,omitempty"`
	Remark       *string             `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalWeather struct {
	AreaName *string       `xml:"AreaName" json:"areaName,omitempty"`
	Sentence *MeteSentence `xml:"Sentence" json:"sentence,omitempty"`
	Weathers []*EbWeather  `xml:"Weather" json:"weathers,omitempty"`
	Time     *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark   *string       `xml:"Remark" json:"remark,omitempty"`
}

type MetePressurePart struct {
	Sentence    *MeteSentence          `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBasePressure      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBasePressure    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBasePressure    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaPressure `xml:"SubArea" json:"subAreas,omitempty"`
	Pressures   []*EbPressure          `xml:"Pressure" json:"pressures,omitempty"`
	Time        *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark      *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaPressure struct {
	AreaName    *string              `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence        `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBasePressure    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBasePressure  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBasePressure  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalPressure `xml:"Local" json:"locals,omitempty"`
	Pressures   []*EbPressure        `xml:"Pressure" json:"pressures,omitempty"`
	Time        *time.Time           `xml:"Time" json:"time,omitempty"`
	Remark      *string              `xml:"Remark" json:"remark,omitempty"`
}

type MeteBasePressure struct {
	TimeModifier *string              `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Pressures    []*EbPressure        `xml:"Pressure" json:"pressures,omitempty"`
	Locals       []*MeteLocalPressure `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time           `xml:"Time" json:"time,omitempty"`
	Remark       *string              `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalPressure struct {
	AreaName  *string       `xml:"AreaName" json:"areaName,omitempty"`
	Sentence  *MeteSentence `xml:"Sentence" json:"sentence,omitempty"`
	Pressures []*EbPressure `xml:"Pressure" json:"pressures,omitempty"`
	Time      *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark    *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteTemperaturePart struct {
	Sentence     *MeteSentence             `xml:"Sentence" json:"sentence,omitempty"`
	Base         *MeteBaseTemperature      `xml:"Base" json:"base,omitempty"`
	Temporaries  []*MeteBaseTemperature    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings    []*MeteBaseTemperature    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas     []*MeteSubAreaTemperature `xml:"SubArea" json:"subAreas,omitempty"`
	Temperatures []*EbTemperature          `xml:"Temperature" json:"temperatures,omitempty"`
	Time         *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark       *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaTemperature struct {
	AreaName     *string                 `xml:"AreaName" json:"areaName,omitempty"`
	Sentence     *MeteSentence           `xml:"Sentence" json:"sentence,omitempty"`
	Base         *MeteBaseTemperature    `xml:"Base" json:"base,omitempty"`
	Temporaries  []*MeteBaseTemperature  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings    []*MeteBaseTemperature  `xml:"Becoming" json:"becomings,omitempty"`
	Locals       []*MeteLocalTemperature `xml:"Local" json:"locals,omitempty"`
	Temperatures []*EbTemperature        `xml:"Temperature" json:"temperatures,omitempty"`
	Time         *time.Time              `xml:"Time" json:"time,omitempty"`
	Remark       *string                 `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseTemperature struct {
	TimeModifier *string                 `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Temperatures []*EbTemperature        `xml:"Temperature" json:"temperatures,omitempty"`
	Locals       []*MeteLocalTemperature `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time              `xml:"Time" json:"time,omitempty"`
	Remark       *string                 `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalTemperature struct {
	AreaName     *string          `xml:"AreaName" json:"areaName,omitempty"`
	Sentence     *MeteSentence    `xml:"Sentence" json:"sentence,omitempty"`
	Temperatures []*EbTemperature `xml:"Temperature" json:"temperatures,omitempty"`
	Time         *time.Time       `xml:"Time" json:"time,omitempty"`
	Remark       *string          `xml:"Remark" json:"remark,omitempty"`
}

type MeteVisibilityPart struct {
	Sentence     *MeteSentence            `xml:"Sentence" json:"sentence,omitempty"`
	Base         *MeteBaseVisibility      `xml:"Base" json:"base,omitempty"`
	Temporaries  []*MeteBaseVisibility    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings    []*MeteBaseVisibility    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas     []*MeteSubAreaVisibility `xml:"SubArea" json:"subAreas,omitempty"`
	Visibilities []*EbVisibility          `xml:"Visibility" json:"visibilities,omitempty"`
	Time         *time.Time               `xml:"Time" json:"time,omitempty"`
	Remark       *string                  `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaVisibility struct {
	AreaName     *string                `xml:"AreaName" json:"areaName,omitempty"`
	Sentence     *MeteSentence          `xml:"Sentence" json:"sentence,omitempty"`
	Base         *MeteBaseVisibility    `xml:"Base" json:"base,omitempty"`
	Temporaries  []*MeteBaseVisibility  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings    []*MeteBaseVisibility  `xml:"Becoming" json:"becomings,omitempty"`
	Locals       []*MeteLocalVisibility `xml:"Local" json:"locals,omitempty"`
	Visibilities []*EbVisibility        `xml:"Visibility" json:"visibilities,omitempty"`
	Time         *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark       *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseVisibility struct {
	TimeModifier *string                `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Visibilities []*EbVisibility        `xml:"Visibility" json:"visibilities,omitempty"`
	Locals       []*MeteLocalVisibility `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark       *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalVisibility struct {
	AreaName     *string         `xml:"AreaName" json:"areaName,omitempty"`
	Sentence     *MeteSentence   `xml:"Sentence" json:"sentence,omitempty"`
	Visibilities []*EbVisibility `xml:"Visibility" json:"visibilities,omitempty"`
	Time         *time.Time      `xml:"Time" json:"time,omitempty"`
	Remark       *string         `xml:"Remark" json:"remark,omitempty"`
}

type MeteSynopsisPart struct {
	Synopses []*EbSynopsis `xml:"Synopsis" json:"synopses"`
	Time     *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark   *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteWaveHeightPart struct {
	Sentence    *MeteSentence            `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWaveHeight      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWaveHeight    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWaveHeight    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaWaveHeight `xml:"SubArea" json:"subAreas,omitempty"`
	WaveHeights []*EbWaveHeight          `xml:"WaveHeight" json:"waveHeights,omitempty"`
	Time        *time.Time               `xml:"Time" json:"time,omitempty"`
	Remark      *string                  `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaWaveHeight struct {
	AreaName    *string                `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence          `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWaveHeight    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWaveHeight  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWaveHeight  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalWaveHeight `xml:"Local" json:"locals,omitempty"`
	WaveHeights []*EbWaveHeight        `xml:"WaveHeight" json:"waveHeights,omitempty"`
	Time        *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark      *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseWaveHeight struct {
	TimeModifier *string                `xml:"TimeModifier" json:"timeModifier,omitempty"`
	WaveHeights  []*EbWaveHeight        `xml:"WaveHeight" json:"waveHeights,omitempty"`
	Locals       []*MeteLocalWaveHeight `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark       *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalWaveHeight struct {
	AreaName    *string         `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence   `xml:"Sentence" json:"sentence,omitempty"`
	WaveHeights []*EbWaveHeight `xml:"WaveHeight" json:"waveHeights,omitempty"`
	Time        *time.Time      `xml:"Time" json:"time,omitempty"`
	Remark      *string         `xml:"Remark" json:"remark,omitempty"`
}

type MetePrecipitationPart struct {
	RefID          *uint8                      `xml:"refID,attr" json:"refID,omitempty"`
	Sentence       *MeteSentence               `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBasePrecipitation      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBasePrecipitation    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBasePrecipitation    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas       []*MeteSubAreaPrecipitation `xml:"SubArea" json:"subAreas,omitempty"`
	Precipitations []*EbPrecipitation          `xml:"Precipitation" json:"precipitations,omitempty"`
	Time           *time.Time                  `xml:"Time" json:"time,omitempty"`
	Remark         *string                     `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaPrecipitation struct {
	AreaName       *string                   `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence             `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBasePrecipitation    `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBasePrecipitation  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBasePrecipitation  `xml:"Becoming" json:"becomings,omitempty"`
	Locals         []*MeteLocalPrecipitation `xml:"Local" json:"locals,omitempty"`
	Precipitations []*EbPrecipitation        `xml:"Precipitation" json:"precipitations,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteBasePrecipitation struct {
	TimeModifier   *string                   `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Precipitations []*EbPrecipitation        `xml:"Precipitation" json:"precipitations,omitempty"`
	Locals         []*MeteLocalPrecipitation `xml:"Local" json:"locals,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalPrecipitation struct {
	AreaName       *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	Precipitations []*EbPrecipitation `xml:"Precipitation" json:"precipitations,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteSnowfallDepthPart struct {
	RefID          *uint8                      `xml:"refID,attr" json:"refID,omitempty"`
	Sentence       *MeteSentence               `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseSnowfallDepth      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseSnowfallDepth    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseSnowfallDepth    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas       []*MeteSubAreaSnowfallDepth `xml:"SubArea" json:"subAreas,omitempty"`
	SnowfallDepths []*EbSnowfallDepth          `xml:"SnowfallDepth" json:"snowfallDepths,omitempty"`
	Time           *time.Time                  `xml:"Time" json:"time,omitempty"`
	Remark         *string                     `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaSnowfallDepth struct {
	AreaName       *string                   `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence             `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseSnowfallDepth    `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseSnowfallDepth  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseSnowfallDepth  `xml:"Becoming" json:"becomings,omitempty"`
	Locals         []*MeteLocalSnowfallDepth `xml:"Local" json:"locals,omitempty"`
	SnowfallDepths []*EbSnowfallDepth        `xml:"SnowfallDepth" json:"snowfallDepths,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseSnowfallDepth struct {
	TimeModifier   *string                   `xml:"TimeModifier" json:"timeModifier,omitempty"`
	SnowfallDepths []*EbSnowfallDepth        `xml:"SnowfallDepth" json:"snowfallDepths,omitempty"`
	Locals         []*MeteLocalSnowfallDepth `xml:"Local" json:"locals,omitempty"`
	Time           *time.Time                `xml:"Time" json:"time,omitempty"`
	Remark         *string                   `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalSnowfallDepth struct {
	AreaName       *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	SnowfallDepths []*EbSnowfallDepth `xml:"SnowfallDepth" json:"snowfallDepths,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteSnowDepthPart struct {
	Base       *MeteBaseSnowDepth `xml:"Base" json:"base,omitempty"`
	SnowDepths []*EbSnowDepth     `xml:"SnowDepth" json:"snowDepths,omitempty"`
	Time       *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark     *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseSnowDepth struct {
	SnowDepths []*EbSnowDepth `xml:"SnowDepth" json:"snowDepths,omitempty"`
	Time       *time.Time     `xml:"Time" json:"time,omitempty"`
	Remark     *string        `xml:"Remark" json:"remark,omitempty"`
}

type MeteHumidityPart struct {
	Sentence    *MeteSentence          `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseHumidity      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseHumidity    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseHumidity    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaHumidity `xml:"SubArea" json:"subAreas,omitempty"`
	Humidities  []*EbHumidity          `xml:"Humidity" json:"humidities,omitempty"`
	Time        *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark      *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaHumidity struct {
	AreaName    *string              `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence        `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseHumidity    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseHumidity  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseHumidity  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalHumidity `xml:"Local" json:"locals,omitempty"`
	Humidities  []*EbHumidity        `xml:"Humidity" json:"humidities,omitempty"`
	Time        *time.Time           `xml:"Time" json:"time,omitempty"`
	Remark      *string              `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseHumidity struct {
	TimeModifier *string              `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Humidities   []*EbHumidity        `xml:"Humidity" json:"humidities,omitempty"`
	Locals       []*MeteLocalHumidity `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time           `xml:"Time" json:"time,omitempty"`
	Remark       *string              `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalHumidity struct {
	AreaName   *string       `xml:"AreaName" json:"areaName,omitempty"`
	Sentence   *MeteSentence `xml:"Sentence" json:"sentence,omitempty"`
	Humidities []*EbHumidity `xml:"Humidity" json:"humidities,omitempty"`
	Time       *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark     *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteTidalLevelPart struct {
	Sentence    *MeteSentence            `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseTidalLevel      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseTidalLevel    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseTidalLevel    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaTidalLevel `xml:"SubArea" json:"subAreas,omitempty"`
	TidalLevels []*EbTidalLevel          `xml:"TidalLevel" json:"tidalLevels,omitempty"`
	Time        *time.Time               `xml:"Time" json:"time,omitempty"`
	Remark      *string                  `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaTidalLevel struct {
	AreaName    *string                `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence          `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseTidalLevel    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseTidalLevel  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseTidalLevel  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalTidalLevel `xml:"Local" json:"locals,omitempty"`
	TidalLevels []*EbTidalLevel        `xml:"TidalLevel" json:"tidalLevels,omitempty"`
	Time        *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark      *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseTidalLevel struct {
	TimeModifier *string                `xml:"TimeModifier" json:"timeModifier,omitempty"`
	TidalLevels  []*EbTidalLevel        `xml:"TidalLevel" json:"tidalLevels,omitempty"`
	Locals       []*MeteLocalTidalLevel `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time             `xml:"Time" json:"time,omitempty"`
	Remark       *string                `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalTidalLevel struct {
	AreaName    *string         `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence   `xml:"Sentence" json:"sentence,omitempty"`
	TidalLevels []*EbTidalLevel `xml:"TidalLevel" json:"tidalLevels,omitempty"`
	Time        *time.Time      `xml:"Time" json:"time,omitempty"`
	Remark      *string         `xml:"Remark" json:"remark,omitempty"`
}

type MeteSunshinePart struct {
	Base      *MeteBaseSunshine `xml:"Base" json:"base,omitempty"`
	Sunshines []*EbSunshine     `xml:"Sunshine" json:"sunshines,omitempty"`
	Time      *time.Time        `xml:"Time" json:"time,omitempty"`
	Remark    *string           `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseSunshine struct {
	Sunshines []*EbSunshine `xml:"Sunshine" json:"sunshines,omitempty"`
	Time      *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark    *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteDetailForecast struct {
	WeatherForecastParts       []*MeteWeatherForecastPart    `xml:"WeatherForecastPart" json:"weatherForecastParts,omitempty"`
	PrecipitationForecastParts []*MetePrecipitationPart      `xml:"PrecipitationForecastPart" json:"precipitationForecastParts,omitempty"`
	SnowfallDepthForecastParts []*MeteSnowfallDepthPart      `xml:"SnowfallDepthForecastPart" json:"snowfallDepthForecastParts,omitempty"`
	WindForecastParts          []*MeteWindForecastPart       `xml:"WindForecastPart" json:"windForecastParts,omitempty"`
	WaveHeightForecastParts    []*MeteWaveHeightForecastPart `xml:"WaveHeightForecastPart" json:"waveHeightForecastParts,omitempty"`
}

type MeteWeatherForecastPart struct {
	RefID       uint8                 `xml:"refID,attr" json:"refID"`
	Sentence    *MeteSentence         `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWeather      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWeather    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWeather    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaWeather `xml:"SubArea" json:"subAreas,omitempty"`
	Weathers    []*EbWeather          `xml:"Weather" json:"weathers,omitempty"`
	Time        *time.Time            `xml:"Time" json:"time,omitempty"`
	Remark      *string               `xml:"Remark" json:"remark,omitempty"`
}

type MeteWindForecastPart struct {
	RefID          uint8              `xml:"refID,attr" json:"refID"`
	Sentence       *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	Base           *MeteBaseWind      `xml:"Base" json:"base,omitempty"`
	Temporaries    []*MeteBaseWind    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings      []*MeteBaseWind    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas       []*MeteSubAreaWind `xml:"SubArea" json:"subAreas,omitempty"`
	WindDirections []*EbWindDirection `xml:"WindDirection" json:"windDirections,omitempty"`
	WindSpeeds     []*EbWindSpeed     `xml:"WindSpeed" json:"windSpeeds,omitempty"`
	Time           *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark         *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteWaveHeightForecastPart struct {
	RefID       uint8                    `xml:"refID,attr" json:"refID"`
	Sentence    *MeteSentence            `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseWaveHeight      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseWaveHeight    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseWaveHeight    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaWaveHeight `xml:"SubArea" json:"subAreas,omitempty"`
	WaveHeights []*EbWaveHeight          `xml:"WaveHeight" json:"waveHeights,omitempty"`
	Time        *time.Time               `xml:"Time" json:"time,omitempty"`
	Remark      *string                  `xml:"Remark" json:"remark,omitempty"`
}

type MeteWeatherCodePart struct {
	WeatherCodes []*EbWeatherCode `xml:"WeatherCode" json:"weatherCodes"`
}

type MeteProbabilityOfPrecipitationPart struct {
	ProbabilityOfPrecipitations []*EbProbabilityOfPrecipitation `xml:"ProbabilityOfPrecipitation" json:"probabilityOfPrecipitations"`
}

type MeteSeaIcePart struct {
	Sentence    *MeteSentence        `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseSeaIce      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseSeaIce    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseSeaIce    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaSeaIce `xml:"SubArea" json:"subAreas,omitempty"`
	SeaIces     []*EbSeaIce          `xml:"SeaIce" json:"seaIces,omitempty"`
	Time        *time.Time           `xml:"Time" json:"time,omitempty"`
	Remark      *string              `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaSeaIce struct {
	AreaName    *string            `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence      `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseSeaIce    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseSeaIce  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseSeaIce  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalSeaIce `xml:"Local" json:"locals,omitempty"`
	SeaIces     []*EbSeaIce        `xml:"SeaIce" json:"seaIces,omitempty"`
	Time        *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark      *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseSeaIce struct {
	TimeModifier *string            `xml:"TimeModifier" json:"timeModifier,omitempty"`
	SeaIces      []*EbSeaIce        `xml:"SeaIce" json:"seaIces,omitempty"`
	Locals       []*MeteLocalSeaIce `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time         `xml:"Time" json:"time,omitempty"`
	Remark       *string            `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalSeaIce struct {
	AreaName *string       `xml:"AreaName" json:"areaName,omitempty"`
	Sentence *MeteSentence `xml:"Sentence" json:"sentence,omitempty"`
	SeaIces  []*EbSeaIce   `xml:"SeaIce" json:"seaIces,omitempty"`
	Time     *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark   *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteIcingPart struct {
	Sentence    *MeteSentence       `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseIcing      `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseIcing    `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseIcing    `xml:"Becoming" json:"becomings,omitempty"`
	SubAreas    []*MeteSubAreaIcing `xml:"SubArea" json:"subAreas,omitempty"`
	Icings      []*EbIcing          `xml:"Icing" json:"icings,omitempty"`
	Time        *time.Time          `xml:"Time" json:"time,omitempty"`
	Remark      *string             `xml:"Remark" json:"remark,omitempty"`
}

type MeteSubAreaIcing struct {
	AreaName    *string           `xml:"AreaName" json:"areaName,omitempty"`
	Sentence    *MeteSentence     `xml:"Sentence" json:"sentence,omitempty"`
	Base        *MeteBaseIcing    `xml:"Base" json:"base,omitempty"`
	Temporaries []*MeteBaseIcing  `xml:"Temporary" json:"temporaries,omitempty"`
	Becomings   []*MeteBaseIcing  `xml:"Becoming" json:"becomings,omitempty"`
	Locals      []*MeteLocalIcing `xml:"Local" json:"locals,omitempty"`
	Icings      []*EbIcing        `xml:"Icing" json:"icings,omitempty"`
	Time        *time.Time        `xml:"Time" json:"time,omitempty"`
	Remark      *string           `xml:"Remark" json:"remark,omitempty"`
}

type MeteBaseIcing struct {
	TimeModifier *string           `xml:"TimeModifier" json:"timeModifier,omitempty"`
	Icings       []*EbIcing        `xml:"Icing" json:"icings,omitempty"`
	Locals       []*MeteLocalIcing `xml:"Local" json:"locals,omitempty"`
	Time         *time.Time        `xml:"Time" json:"time,omitempty"`
	Remark       *string           `xml:"Remark" json:"remark,omitempty"`
}

type MeteLocalIcing struct {
	AreaName *string       `xml:"AreaName" json:"areaName,omitempty"`
	Sentence *MeteSentence `xml:"Sentence" json:"sentence,omitempty"`
	Icings   []*EbIcing    `xml:"Icing" json:"icings,omitempty"`
	Time     *time.Time    `xml:"Time" json:"time,omitempty"`
	Remark   *string       `xml:"Remark" json:"remark,omitempty"`
}

type MeteReliabilityClassPart struct {
	ReliabilityClasses []*EbReliabilityClass `xml:"ReliabilityClass" json:"reliabilityClasses"`
}

type MeteReliabilityValuePart struct {
	ReliabilityValues []*EbReliabilityValue `xml:"ReliabilityValue" json:"reliabilityValues"`
}

type MetePossibilityRankOfWarningPart struct {
	PossibilityRankOfWarnings []*EbPossibilityRankOfWarning `xml:"PossibilityRankOfWarning" json:"possibilityRankOfWarnings"`
}

type MeteClassPart struct {
	TyphoonClass   *EbTyphoonClass   `xml:"TyphoonClass" json:"typhoonClass,omitempty"`
	AreaClass      *EbAreaClass      `xml:"AreaClass" json:"areaClass,omitempty"`
	IntensityClass *EbIntensityClass `xml:"IntensityClass" json:"intensityClass,omitempty"`
	Time           *time.Time        `xml:"Time" json:"time,omitempty"`
	Remark         *string           `xml:"Remark" json:"remark,omitempty"`
}

type MeteTyphoonNamePart struct {
	Name     *string    `xml:"Name" json:"name,omitempty"`
	NameKana *string    `xml:"NameKana" json:"nameKana,omitempty"`
	Number   *string    `xml:"Number" json:"number,omitempty"`
	Time     *time.Time `xml:"Time" json:"time,omitempty"`
	Remark   *string    `xml:"Remark" json:"remark,omitempty"`
}

type MeteCenterPart struct {
	Coordinates        []*EbCoordinate `xml:"Coordinate" json:"coordinates,omitempty"`
	ProbabilityCircles []*EbCircle     `xml:"ProbabilityCircle" json:"probabilityCircles,omitempty"`
	Location           *string         `xml:"Location" json:"location,omitempty"`
	Directions         []*EbDirection  `xml:"Direction" json:"directions,omitempty"`
	Speeds             []*EbSpeed      `xml:"Speed" json:"speeds,omitempty"`
	Pressure           *EbPressure     `xml:"Pressure" json:"pressure,omitempty"`
	Radiuses           []*EbRadius     `xml:"Radius" json:"radiuses,omitempty"`
	Time               *time.Time      `xml:"Time" json:"time,omitempty"`
	Remark             *string         `xml:"Remark" json:"remark,omitempty"`
}

type MeteCoordinatePart struct {
	Coordinates []*EbCoordinate `xml:"Coordinate" json:"coordinates,omitempty"`
	Lines       []*EbCoordinate `xml:"Line" json:"lines,omitempty"`
	Polygons    []*EbCoordinate `xml:"Polygon" json:"polygons,omitempty"`
	Time        *time.Time      `xml:"Time" json:"time,omitempty"`
	Remark      *string         `xml:"Remark" json:"remark,omitempty"`
}

type MeteIsobarPart struct {
	Pressure EbPressure    `xml:"Pressure" json:"pressure"`
	Line     *EbCoordinate `xml:"Line" json:"line,omitempty"`
	Polygon  *EbCoordinate `xml:"Polygon" json:"polygon,omitempty"`
}

type MeteWaterLevelPart struct {
	WaterLevels []*EbWaterLevel `xml:"WaterLevel" json:"waterLevels,omitempty"`
}

type MeteFloodAssumptionTable struct {
	Area                 MeteArea                   `xml:"Area" json:"area"`
	FloodAssumptionParts []*MeteFloodAssumptionPart `xml:"FloodAssumptionPart" json:"floodAssumptionParts,omitempty"`
	Remark               *string                    `xml:"Remark" json:"remark,omitempty"`
}

type MeteFloodAssumptionPart struct {
	FloodAssumptionArea   *string         `xml:"FloodAssumptionArea" json:"floodAssumptionArea,omitempty"`
	AttainmentTime        *EbDateTime     `xml:"AttainmentTime" json:"attainmentTime,omitempty"`
	FloodDepths           []*EbFloodDepth `xml:"FloodDepth" json:"floodDepths,omitempty"`
	AttainmentDeepestTime *EbDateTime     `xml:"AttainmentDeepestTime" json:"attainmentDeepestTime,omitempty"`
}

type MeteDischargePart struct {
	Discharges []*EbDischarge `xml:"Discharge" json:"discharges,omitempty"`
}

type MeteHydrometricStationPart struct {
	Area           MeteArea                          `xml:"Area" json:"area"`
	ChargeSections []string                          `xml:"ChargeSection" json:"chargeSections,omitempty"`
	Criterias      []*MeteHydrometricStationCriteria `xml:"Criteria" json:"criterias"`
	Remark         *string                           `xml:"Remark" json:"remark,omitempty"`
}

type MeteHydrometricStationCriteria struct {
	WaterLevels []*EbWaterLevel `xml:"WaterLevel" json:"waterLevels,omitempty"`
	Discharges  []*EbDischarge  `xml:"Discharge" json:"discharges,omitempty"`
}

type MeteSignificancyPart struct {
	Base MeteBaseSignificancy `xml:"Base" json:"base"`
}

type MeteBaseSignificancy struct {
	Significancies []*MeteSignificancy      `xml:"Significancy" json:"significancies,omitempty"`
	Sentence       *MeteSentence            `xml:"Sentence" json:"sentence,omitempty"`
	PeakTime       *MeteForecastTerm        `xml:"PeakTime" json:"peakTime,omitempty"`
	Attention      *MeteAttention           `xml:"Attention" json:"attention,omitempty"`
	Addition       *MeteAddition            `xml:"Addition" json:"addition,omitempty"`
	Locals         []*MeteLocalSignificancy `xml:"Local" json:"locals,omitempty"`
}

type MeteLocalSignificancy struct {
	AreaName       string              `xml:"AreaName" json:"areaName"`
	Significancies []*MeteSignificancy `xml:"Significancy" json:"significancies,omitempty"`
	Sentence       *MeteSentence       `xml:"Sentence" json:"sentence,omitempty"`
	PeakTime       *MeteForecastTerm   `xml:"PeakTime" json:"peakTime,omitempty"`
	Attention      *MeteAttention      `xml:"Attention" json:"attention,omitempty"`
	Addition       *MeteAddition       `xml:"Addition" json:"addition,omitempty"`
}

type MeteSignificancy struct {
	Type      string  `xml:"type,attr" json:"type"`
	RefID     *uint8  `xml:"refID,attr" json:"refID,omitempty"`
	Name      string  `xml:"Name" json:"name"`
	Code      string  `xml:"Code" json:"code"`
	Condition *string `xml:"Condition" json:"condition,omitempty"`
	Remark    *string `xml:"Remark" json:"remark,omitempty"`
}
