name: Test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Test
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Test jmaxml-json-types
        run: npm install && npm run test
        working-directory: ./jmaxml-json-types

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          working-directory: ./jmaxml-rs
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
