[package]
name = "jmaxml"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
iso8601-duration = { version = "0.2.0", features = ["chrono", "serde"] }
serde = { version = "1.0.204", features = ["derive"] }
quick-xml = { version = "0.36.1", features = ["serialize"] }
serde_json = "1.0.122"

[dev-dependencies]
glob = "0.3.1"
serde_json = "1.0.122"
